### ISSUE TITLE
tree-view fails to activate on start up of Atom 1.8.0

### ISSUE THREAD

**Issue by fusion809** [tensor5/arch-atom#14]
Hi,

I started Atom, that I built myself using your PKGBUILD, after installing apm and electron OFC from this repo and I got this error:

![](http://i.imgur.com/xX6rnD6.png)

Here is the full error report:

--------------------------------------------------------------------------
[Enter steps to reproduce below:]

1. Started Atom (via running `atom .` in the git repo of this package)

**Atom Version**: 1.8.0
**System**: "Arch Linux"
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package, v0.205.0

### Stack Trace

Failed to activate the tree-view package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.basename (path.js:1355:5)
  at Object.shouldAttach (/usr/lib/atom/node_modules/tree-view/lib/main.js:114:23)
  at Object.activate (/usr/lib/atom/node_modules/tree-view/lib/main.js:16:16)
  at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:183:20)
  at /usr/lib/atom/src/package.js:156:32
  at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
  at /usr/lib/atom/src/package.js:149:26
  at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:530:21)
  at /usr/lib/atom/src/package-manager.js:511:29
  at Config.module.exports.Config.transactAsync (/usr/lib/atom/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/lib/atom/src/package-manager.js:506:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/lib/atom/src/package-manager.js:489:46)
  at /usr/lib/atom/src/atom-environment.js:754:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.lisp": [
        ".emacs",
        ".spacemacs"
      ],
      "source.python": [
        "BUCK"
      ],
      "text.html.basic": [
        "ejs",
        "htm",
        "html",
        "kit",
        "shtml",
        "tmpl",
        "tpl",
        "xhtml"
      ]
    },
    "disabledPackages": [
      "linter-markdown",
      "language-gfm"
    ],
    "projectHome": "/home/fusion809/GitHub/mine",
    "themes": [
      "fusion-ui",
      "dark-fusion-syntax"
    ]
  },
  "tree-view": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.0.2
autocomplete-modules, v1.5.1
autocomplete-php, v0.3.7
autocomplete-python, v1.7.4
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
file-icons, v1.7.13
go-config, v1.1.4
go-get, v1.0.3
linter-coffeescript, v1.0.0
linter-jslint, v10.2.0
minimap, v4.24.3
package-sync, v1.1.0
pigments, v0.29.1
platformio-ide-terminal, v2.0.10

# Dev
No dev packages
```
--------------------------------------------------------------------------

This error does **not** occur on my own build of Atom (built using [this](https://github.com/fusion809/atom-editor-arch/) repo's files), with more traditional build settings, so I felt this error is probably not something I should report to the [git repo of tree-view](https://github.com/atom/tree-view). The error appears intermittent, after I got this error I closed Atom and re-opened with the same command (`atom .` in this git repo) and the error message was gone and tree view opened normally.

Thanks for your time,
Brenton

**Comment by tensor5** [comment]
This is again caused by the fact that we use Electron 1.2, which is based on Node 6. To be precise it's this commit nodejs/node@08085c49b6e49ecfffd638c6cd46f4de639ae4f4. I'll see if I can make a patch and open a pull request.

**Comment by tensor5** [comment]
https://github.com/atom/tree-view/issues/863#issuecomment-224217556
