### ISSUE TITLE
Failed to download atom editor. Server timed out

### ISSUE THREAD

**Issue by chanakaDe** [tensor5/arch-atom#15]
error: failed retrieving file 'atom-editor-1.7.2-1-x86_64.pkg.tar.xz' from apricityos.com : Resolving timed out after 10520 milliseconds.
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

*****When i was going to install atom in my arch , this error occurred.

**Comment by tensor5** [comment]
You are talking about someone else's repository.

Settings for this repository are [here](https://wiki.archlinux.org/index.php/Unofficial_user_repositories#atom), and package name is simply `atom`:

```sh
$ pacman -S atom
```

**Comment by chanakaDe** [comment]
When I use the command "pacman -S atom" , there's also an error.
This is the error message "error: target not found: atom".
What's this ? Something wrong in my system ?

**Comment by tensor5** [comment]
First you should add the `[atom]` repository to your `/etc/pacman.conf`. Add the following two lines at the end of `/etc/pacman.conf`:

```
[atom]
Server = http://noaxiom.org/$repo/$arch
```

Second you need to add and sign my PGP key, with this commands (as root)

```
# pacman-key -r B0544167
# pacman-key --lsign-key B0544167
```

Lastly you can install the package with `pacman -S atom`. Try and let me know if you still have problems.

**Comment by chanakaDe** [comment]
warning: database file for 'atom' does not exist
error: target not found: atom
  
Same error :(
It's ok then. I think my machine cannot install Atom.... :( 
Plz tell me if u have any suggestions bro :(
Did everything u said earlier

**Comment by tensor5** [comment]
I assume your already added the `[atom]` repository and PGP key, as my previous post. I forgot to mention that you should refresh the db first:

```
# pacman -Sy
# pacman -S atom
```

**Comment by chanakaDe** [comment]
chanaka  ~  sudo pacman -Sy                                              1 
:: Synchronizing package databases...
error: failed retrieving file 'apricity-core.db' from apricityos.com : Resolving timed out after 10521 milliseconds
error: failed to update apricity-core (download library error)
 core is up to date
 extra is up to date
 multilib is up to date
 community is up to date
error: failed retrieving file 'atom.db' from noaxiom.org : Resolving timed out after 10514 milliseconds
error: failed to update atom (download library error)


This is the output :+1: 
Yeah I added all the keys and config update as you said :)

**Comment by tensor5** [comment]
It might be a network problem on your side. Can you access `http://noaxiom.org/atom/x86_64/` with your browser?

**Comment by chanakaDe** [comment]
Yeah I can. There's a table of .deb versions.....
Name	Last modified	Size like that.
I really want to install Atom. Because I used in Windows and it's really nice and i'm used to it.
No any solutions ?

**Comment by tensor5** [comment]
By chance, are you on a 32bit system? Currently I only package for x86_64.

**Comment by chanakaDe** [comment]
Nope.. I'm using 64 Bit...

**Comment by tensor5** [comment]
Since you can access `http://noaxiom.org/atom/x86_64`, for now you can download the packages manually and install them with `pacman -U`, until we figure out. Download `electron-1.2.5-1-x86_64.pkg.tar.xz`, `nodejs-atom-package-manager-1.11.4-1-x86_64.pkg.tar.xz` and `atom-1.8.0-3-x86_64.pkg.tar.xz` and install them in this order:

```
# pacman -U electron-1.2.5-1-x86_64.pkg.tar.xz
# pacman -U nodejs-atom-package-manager-1.11.4-1-x86_64.pkg.tar.xz
# pacman -U atom-1.8.0-3-x86_64.pkg.tar.xz
```

**Comment by chanakaDe** [comment]
WOW.. This works...
Thank you very much :+1:
