### ISSUE TITLE
Manu bar with white text on light backgroud

### ISSUE THREAD

**Issue by echpiel** [tensor5/arch-atom#18]
I am using Gnome Desktop, everything up to date (including Atom from this repository).

The text in the menu bar is rendered in white on some light grey background, making it very difficult to read.

![image](https://cloud.githubusercontent.com/assets/12746147/16758471/feb9883c-4811-11e6-81fc-3cfa2746d798.png)

In similar systems (same Desktop and version of Atom, for example in Fedora 24) there is no problem with the menu bar rendering and the proper GTK colors are used.

![image](https://cloud.githubusercontent.com/assets/12746147/16758528/5af9f30c-4812-11e6-8cad-936c486f47f2.png)

**Comment by tensor5** [comment]
This happened after switching to GTK3 (see https://github.com/tensor5/arch-atom/issues/10#issuecomment-227922223). Other distributions opt for the more traditional GTK2 build.

I'm trying to solve it. Meantime I recommend using the Auto Hide Menu Bar option, which allows you to toggle the menu bar with `Alt`, and enjoy the GTK3 file chooser.
