### ISSUE TITLE
Missing/Incorrect dependency on explict version of libhttpparser

### ISSUE THREAD

**Issue by willotter** [tensor5/arch-atom#21]
I have just upgraded electron (version `1.2.7-2`) and I get the following error:
```
/usr/lib/electron/electron: error while loading shared libraries: libhttp_parser.so.2.7.0: cannot open shared object file: No such file or directory
```
`http-parser` package appears to updated two days ago https://www.archlinux.org/packages/community/i686/http-parser/ . Is there any reason for the explicit dependency on `libhttp_parser.so.2.7.0` rather than `libhttp_parser.so`?

My workaround for the moment is to the symlink `libhttp_parser.so.2.7.0` to `libhttp_parser.so`

Let me know if you need anymore info?

**Comment by tensor5** [comment]
`http-parser-2.7.1` for x86_64 showed up in the update just few hours ago. The library soname is `libhttp_parser.so.2.7.x`, hence the explicit dependency on that version.
I will rebuild tomorrow.

**Comment by repsac-by** [comment]
quick fix
```shell
pkgname=electron-libhttp-parser-quickfix
pkgver=1.0
pkgrel=1
arch=('any')
license=('GPL')
depends=('electron<=1.2.7-2' 'http-parser=2.7.1')
conflicts=('electron>1.2.7-2')
package() {
    install -d "${pkgdir}/usr/lib"

    cd "$pkgdir/usr/lib"
    ln -sf libhttp_parser.so.2.7.1 libhttp_parser.so.2.7.0
}
```

save and run `makepkg -i`
