### ISSUE TITLE
Atom's relocation to the [community] repository

### ISSUE THREAD

**Issue by fusion809** [tensor5/arch-atom#35]
Hi,

I noticed in your last commit (88ca674) that you mentioned this Atom package moving into the `[community]` repo and I must say it's about time! :+1:  The `atom-editor` package has been the most voted package in the AUR for so long that I'm surprised it hasn't already been added to the `[community]` repository. Although I'd like to suggest that the Atom package added to the `[community]` repo be as similar to the official Atom build as possible while still using the latest APM and Electron versions. Where APM is also provided by the `atom` package (i.e., there shouldn't be a separate `apm` package as APM has no value outside of being used with and alongside Atom, unlike Electron which can be used as a standalone app). I'd also recommend the ASAR packaging mentioned in #30 be added. 

I thought I'd open this issue in order to start a discussion about any changes to be made to the packages in this repo before it is added to the `[community]` repository. 

Thanks for your time,
Brenton

**Comment by tensor5** [comment]
@fusion809 you might want to read the discussion in #24 about apm being a separate package: @City-busz made a point there that apm could be used as a build tool for other Electron based packages. We will see how that works in real world.

Regarding asar packaging, I will implement it once things settle down a little; it's still convenient for me sometimes to be able to quickly look at Atom modules code and make modifications.
