### ISSUE TITLE
What's up with the GTK2 build time dep for Electron?

### ISSUE THREAD

**Issue by SShrike** [tensor5/arch-atom#37]
I was looking at the Electron PKGBUILD and noticed that it has a [makedepend on GTK2](https://github.com/tensor5/arch-atom/blob/master/electron/PKGBUILD#L14), despite the fact that it's apparently built with GTK3 support now as of #10 and has a runtime dependency on GTK3.

Is this an error or is it some intricacy of Electron?

**Comment by tensor5** [comment]
Right now Electron has no runtime or buildtime dependency on GTK2, however during the initial stage of the build process the Chromium part of the build does `pkg-config gtk-2.0`; rather than patching Chromium I opted for including gtk2 in makedepends.

**Comment by SShrike** [comment]
I see now, thanks for the clarification.
