### ISSUE TITLE
Visual Bugs in the Settings View

### ISSUE THREAD

**Issue by SShrike** [tensor5/arch-atom#38]
There seems to be some visual bugs in the settings view, I've attached [a video](https://github.com/tensor5/arch-atom/files/420153/2016-08-16.23-45-45.tar.gz) as it's simpler than trying to explain.

The visual bugs happen when I launch Atom in safe mode as well, so I don't think it has anything to do with my packages. I'm running a completely updated (as of 11:51 PM NZST, 16/08/16), stock Arch system with the Nvidia drivers and Plasma 5.

**Comment by tensor5** [comment]
Thanks for reporting.

**Comment by SShrike** [comment]
I'm currently at my PC, so if there's any more information you need, don't hesitate to ask.

**Comment by tensor5** [comment]
I'm on `Settings > Themes` and I opened the developer console (`CTRL+ SHIFT+ I`). I don't understand why there is that extra vertical space in the body of `<div class="section packages themes-panel">...</div>`.

**Comment by SShrike** [comment]
Can you not see it on your installed copy?

**Comment by tensor5** [comment]
I can. Trying to share what I'm doing, in case somebody wants to help.

**Comment by SShrike** [comment]
Wohoo! Thanks for the speedy fix :)

What exactly was causing it, considering  `height: 100%;` works in stock Atom?

**Comment by tensor5** [comment]
`height: 100%` seems wrong to me regardless, I've know idea why that was not causing troubles in stock Atom. I'm going to open a PR in `settings-view` later on.
