### ISSUE TITLE
The "Reload Window" keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by SShrike** [tensor5/arch-atom#39]
I can't reload the window using the `Ctrl+Alt+R` keyboard shortcut, it does however work if I manually click on the menu bar entry under View -> Developer -> Reload Window. The issue happens when Atom is launched in safe mode as well.

**Comment by tensor5** [comment]
Thanks, I'll look into it.

**Comment by tensor5** [comment]
`Ctrl-Alt-R` works for me. Open `Keybindings` and see if by chance you overwrote it.

**Comment by SShrike** [comment]
My keymap is left as default and the issue still persists, also the default shortcut is shown in the menu bar as well.

Perhaps it's related to me using KDE/Plasma 5? Are you using Gnome?

**Comment by SShrike** [comment]
Further investigation with the keybinding resolver shows that Atom (or Electron?) is only picking up Ctrl and Alt from the sequence. It seems to only not pick up the R key though, as the rest work fine. I'm going to got look through the Plasma/KDE keybindings to see if something is blocking it.

**Comment by SShrike** [comment]
Okay, I've found what it was, the global keyboard shortcut "Manually Invoke Action on Current Clipboard" seemed to be blocking it.

![screenshot_20160818_154523](https://cloud.githubusercontent.com/assets/4061736/17761381/d38ad22c-655a-11e6-83d8-6168113a4a62.png)
