### ISSUE TITLE
apm install fails to runs correctly with Node.js 6.5.0 in the atom PKGBUILD

### ISSUE THREAD

**Issue by fusion809** [tensor5/arch-atom#40]
Hi,

I've noticed that since the release of Node.js 6.5.0 the running of `apm install` in Atom's top-level source directory (as the atom PKGBUILD does at [line 72](https://github.com/tensor5/arch-atom/blob/master/atom/PKGBUILD#L72)) fails, as `apm install` just freezes and doesn't proceed past the stage of:

```bash
Installing modules
```

even after waiting for >2 hours! I've started a new task at the Arch Linux Bugzilla ([FS#50164](https://bugs.archlinux.org/task/50614)) regarding this, but I thought I'd give ya a heads up, in the hope that the extra time that alerting ya before you're assigned to this task on the Bugzilla affords ya, helps ya to fix this bug. 

How to reproduce:

Run `makepkg -sifC --noconfirm` in the `atom` subdirectory of this repository, or (and yeah this will be faster) get the Atom source for v1.9.9, go into the top-level directory of the source code and run `apm install`. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Just to be clear this error **did not** occur with Node.js 6.4.0. I've been forced to downgrade to Node.js 6.4.0 in order to get past this error. This error **does not** seem to affect the installing of extra APM packages (e.g., with `apm install script`), once Atom has been installed. It only seems to be occur when it is run in Atom's source directory.

**Comment by tensor5** [comment]
Hi,

I successfully built `atom-1.9.9-3`  a few hours ago with Node 6.5.0. Could it be a temporary network problem on your side?

**Comment by fusion809** [comment]
Did you do a clean build? (i.e., did ya pass the `-C` option to `makepkg`?) Good question, but sadly I doubt it. My net is excellent and with Node.js 6.4.0 everything builds fine. With 6.5.0 I've tried at least 5 times with no success. Every time there was nothing wrong with my net, I could access web pages, perform downloads and uploads without a problem.

**Comment by tensor5** [comment]
I built on Arch's server in a clean chroot environment. Tried now on my laptop and it's installing.
I've no idea right now on what can cause this issue. Try a few hours later and let me know if it persists.

**Comment by tensor5** [comment]
https://bugs.archlinux.org/task/50614.
