### ISSUE TITLE
Atom 1.11 is out

### ISSUE THREAD

**Issue by rumpelsepp** [tensor5/arch-atom#41]
http://blog.atom.io/2016/10/11/atom-1-11.html

**Comment by juvevood** [comment]
### 1.12 is out  >.<

**Comment by rumpelsepp** [comment]
1.12 is beta, isn't it?

On October 20, 2016 5:07:06 AM GMT+02:00, juve <notifications@github.com> wrote:
>### 1.12 is out  >.<

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SShrike** [comment]
Yes, [1.12 is the current beta](http://blog.atom.io/2016/10/11/atom-1-11.html#atom-112-beta).

**Comment by rumpelsepp** [comment]
Then you should report it to the respective AUR packages. This is the repo for atom stable.

On October 20, 2016 6:50:16 AM GMT+02:00, Severen Redwood <notifications@github.com> wrote:
>Yes, [1.12 is the current
>beta](http://blog.atom.io/2016/10/11/atom-1-11.html#atom-112-beta).

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fusion809** [comment]
I'm surprised it's taking so long for Atom 1.11.x to be added to the `[community]` repo. Guessing @tensor5 is having trouble thanks to the new build system for Atom &geq;1.11.

**Comment by tensor5** [comment]
I've been packed with work these weeks. I can do boilerplate updates, but for atom 1.11 you'll have to wait the weekend.
