### ISSUE TITLE
Any interest in providing a Visual Studio Code (OSS) package for Arch Linux built on this repo's build of Electron?

### ISSUE THREAD

**Issue by fusion809** [tensor5/arch-atom#47]
Hi,

I realize this is off-topic for a bug-tracker but as I don't know your email address this seems like the best way to contact ya with this question. I am just curious if you have any interest in providing a Visual Studio Code (OSS) package in the `[community]` repo of Arch Linux that utilizes the `electron` package you provide in the `[community]` repo?

Thanks for your time,
Brenton

**Comment by tensor5** [comment]
Hi,

Yes, I do have a plan to bring Visual Studio Code to [community]. BTW my email is at the second line of all my [PKGBUILD](https://github.com/tensor5/arch-atom/blob/master/electron/PKGBUILD#L2)s :)

**Comment by fusion809** [comment]
Rofl, sorry and thanks. I'll close this issue as it's now resolved.
