### ISSUE TITLE
noaxiom.org down?

### ISSUE THREAD

**Issue by yohanboniface** [tensor5/arch-atom#49]
I got timeout errors.

http://downforeveryoneorjustme.com/noaxiom.org seems to agree on this. :/

Thanks! :)

**Comment by tensor5** [comment]
Should be up now. BTW, packages are in [community].

**Comment by skerit** [comment]
@tensor5 Seems like it's down again!

**Comment by tensor5** [comment]
@skerit, packages are in [community].
