### ISSUE TITLE
Failed to get atom.db

### ISSUE THREAD

**Issue by tirrorex** [tensor5/arch-atom#6]
sudo pacman -Sy atom gives me 404 error, seems the request cannot get atom.db from noaxiom.org thus installation of atom is failing atom
Tried with atom-editor also as i wasn't sure which one is proper, same thing

**Comment by tensor5** [comment]
I tried `sudo pacman -Syy atom` right now and it works for me. Can you try again? It might be a temporary network problem.

**Comment by tirrorex** [comment]
I can confirm i still have the same issue.
I had the repository by doing 
1.  pacman-key -r B0544167
2. pacman-key -f B0544167
3. pacman-key --lsign-key B0544167
4. echo "[atom]
Server = http://noaxiom.org/$repo/$arch" >> /etc/pacman.conf
5. sudo pacman -Syy atom

atom.db requested url returned error: 404

**Comment by tensor5** [comment]
Can you navigate to http://noaxiom.org/atom/x86_64/ with your browser and download a package manually?

**Comment by tensor5** [comment]
I assume the issue is solved.

**Comment by sabian2008** [comment]
I'm having this issue too: atom.db 404 error while database syncing.

However using the web browser I'm able to see the files. Nonetheless I didn't download it manually because the folder it's name x86_64 and I'm in an i686 system. Could that be the problem in pacman too? I think it might be looking for http://noaxiom.org/atom/i686.

**Comment by tensor5** [comment]
@sabian2008, currently I don't provide i686 packages, but stay tuned, I might build for i686 in the near future.

**Comment by sabian2008** [comment]
Sorry for that. I saw some i686 references in the commits and got excited. Probably should have read better.

Thanks for the quick response and for your work.

Cheers,

**Comment by tensor5** [comment]
@sabian2008 Atom for i686 is now in [community].
