### ISSUE TITLE
Error when start the Atom Package Manager

### ISSUE THREAD

**Issue by wyea** [tensor5/arch-atom#8]
Hi Nicola,
I'm getting the following error. It's more likely a nodejs problem though... But maybe you know how to fix it? It used to work fine a couple days ago... 
Thanks

$ apm update --all
(node:6266) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:6266) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:541:32)

**Comment by tensor5** [comment]
Thank you for reporting the issue, I didn't do `apm update` today so I missed it. It's due to `nodejs-6.0.0` and fix is on the way.

**Comment by wyea** [comment]
Hi Nicola! Thank you so much for the fix!
Although now apm works, I'm still getting a warning I didn't have before... We should wait until the atom team updates the dependencies of the apm, I guess...
Thanks! :-)

```
apm update --all
(node:23715) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:23715) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Package Updates Available (0)
```

**Comment by tensor5** [comment]
I notice that. Fortunately it does not affect the behavior of 'Packages and 'Updates' inside Atom's 'Settings'.
The problem is that upstream they ship an old vesion on Node (v0.10.40) together with apm, while we use Arch Linux's `nodejs` (I don't like duplication, which seems to be the trend nowadays).

**Comment by SShrike** [comment]
@tensor5, the issue with Keytar might be fixed now: atom/node-keytar#40 and atom/node-keytar#41.

**Comment by tensor5** [comment]
Apm is already picking up the latest `keytar`.

**Comment by SShrike** [comment]
Sorry hahaha, I missed the obvious message "apm: don't pin keytar version" right above my comment.
